steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/web:latest",
        ".",
      ]
timeout: 300s
images:
  - ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/web:latest
options:
  logging: CLOUD_LOGGING_ONLY
