steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/images/${REPO_NAME}:${COMMIT_SHA}",
        "-t",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/images/${REPO_NAME}:latest",
        ".",
      ]
    env:
      - BASE_URL=${_BASE_URL}
      - ASSETS_HOSTNAME=${_ASSETS_HOSTNAME}
      - ASSETS_PATHNAME=${_ASSETS_PATHNAME}
timeout: 300s
images:
  - ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/images/${REPO_NAME}:${COMMIT_SHA}
  - ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/images/${REPO_NAME}:latest
substitutions:
  _BASE_URL: NONE
  _ASSETS_HOSTNAME: NONE
  _ASSETS_PATHNAME: NONE
options:
  logging: CLOUD_LOGGING_ONLY
