import Head from "next/head";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Xu Chen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main className="flex justify-center items-center h-[50vh]">
        <h1 className="font-bold text-5xl">Welcome to My Website</h1>
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
