import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Xu Chen</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex justify-center items-center h-[50vh]">
        <h1 className="font-bold text-5xl">Welcome to My Website</h1>
      </main>
    </>
  );
}
